"""Export Shingox's CC0 humanoid Blender mesh into YinQiDao's static GPUI mesh source.

Usage:
    blender --background /path/to/HumanoidBaseMesh_new.blend \
        --python tools/audio_debug/export_humanoid_cc0.py -- \
        src/ui/audio_debug_humanoid_generated.rs

Source asset:
    Humanoid Low Poly Mesh (With Basic Face)
    Author: Shingox
    License: CC0
    Original file: HumanoidBaseMesh_new.blend
    https://opengameart.org/content/humanoid-low-poly-mesh-with-basic-face

The generated Rust file is runtime-only static geometry. YinQiDao never needs Blender, file I/O,
or a general-purpose model parser in the realtime/debug rendering path.
"""

from __future__ import annotations

import pathlib
import sys

import bpy

TARGET_HEIGHT_METERS = 1.72
# ListenerPose.position is the acoustic head center. A neutral human head center is roughly this
# fraction below the top of a standing humanoid. The exact acoustic ear positions remain controlled
# by ListenerPose::ear_positions(), not by the visual mesh.
HEAD_CENTER_FROM_TOP_FRACTION = 0.075


def output_path() -> pathlib.Path:
    args = sys.argv
    if "--" not in args:
        raise SystemExit("missing '-- <output.rs>' argument")
    rest = args[args.index("--") + 1 :]
    if len(rest) != 1:
        raise SystemExit("expected exactly one output Rust path")
    return pathlib.Path(rest[0]).resolve()


def collect_mesh() -> tuple[list[tuple[float, float, float]], list[int]]:
    depsgraph = bpy.context.evaluated_depsgraph_get()
    vertices: list[tuple[float, float, float]] = []
    indices: list[int] = []

    for obj in bpy.context.scene.objects:
        if obj.type != "MESH" or obj.hide_render:
            continue

        evaluated = obj.evaluated_get(depsgraph)
        mesh = evaluated.to_mesh(preserve_all_data_layers=False, depsgraph=depsgraph)
        try:
            mesh.calc_loop_triangles()
            base = len(vertices)
            transform = evaluated.matrix_world
            for vertex in mesh.vertices:
                co = transform @ vertex.co
                vertices.append((float(co.x), float(co.y), float(co.z)))
            for triangle in mesh.loop_triangles:
                indices.extend(base + int(index) for index in triangle.vertices)
        finally:
            evaluated.to_mesh_clear()

    if not vertices or not indices:
        raise SystemExit("no mesh geometry found in the Blender scene")
    return vertices, indices


def normalize(vertices: list[tuple[float, float, float]]) -> list[tuple[float, float, float]]:
    min_x = min(v[0] for v in vertices)
    max_x = max(v[0] for v in vertices)
    min_y = min(v[1] for v in vertices)
    max_y = max(v[1] for v in vertices)
    min_z = min(v[2] for v in vertices)
    max_z = max(v[2] for v in vertices)

    height = max_z - min_z
    if height <= 1.0e-6:
        raise SystemExit("humanoid mesh has zero/invalid height")
    scale = TARGET_HEIGHT_METERS / height

    center_x = (min_x + max_x) * 0.5
    center_y = (min_y + max_y) * 0.5
    head_center_z = max_z - height * HEAD_CENTER_FROM_TOP_FRACTION

    result: list[tuple[float, float, float]] = []
    for x, y, z in vertices:
        # Blender convention: X right, Y depth, Z up.
        # YinQiDao convention: X right, Y up, Z forward. Blender's common character front is -Y.
        engine_x = (x - center_x) * scale
        engine_y = (z - head_center_z) * scale
        engine_z = -(y - center_y) * scale
        result.append((engine_x, engine_y, engine_z))
    return result


def write_rust(path: pathlib.Path, vertices: list[tuple[float, float, float]], indices: list[int]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// @generated by tools/audio_debug/export_humanoid_cc0.py\n")
        out.write("// Source: Shingox, Humanoid Low Poly Mesh (With Basic Face), CC0.\n\n")
        out.write("pub(crate) const HUMANOID_ASSET_READY: bool = true;\n")
        out.write("pub(crate) const HUMANOID_VERTICES: &[[f32; 3]] = &[\n")
        for x, y, z in vertices:
            out.write(f"    [{x:.8f}, {y:.8f}, {z:.8f}],\n")
        out.write("];\n")
        out.write("pub(crate) const HUMANOID_INDICES: &[u32] = &[\n")
        for offset in range(0, len(indices), 18):
            chunk = indices[offset : offset + 18]
            out.write("    " + ", ".join(str(index) for index in chunk) + ",\n")
        out.write("];\n")


def main() -> None:
    path = output_path()
    vertices, indices = collect_mesh()
    vertices = normalize(vertices)
    write_rust(path, vertices, indices)
    print(f"wrote {len(vertices)} vertices / {len(indices) // 3} triangles -> {path}")


if __name__ == "__main__":
    main()
