// Generated by tools/audio_debug/export_humanoid_cc0.py.
//
// Source target:
//   Humanoid Low Poly Mesh (With Basic Face)
//   Author: Shingox
//   License: CC0
//   Original file: HumanoidBaseMesh_new.blend
//
// The repository keeps an empty generated payload so normal builds do not depend on Blender or a
// network download. Run the exporter locally to replace this file with the actual CC0 mesh.

pub(crate) const HUMANOID_ASSET_READY: bool = false;
pub(crate) const HUMANOID_VERTICES: &[[f32; 3]] = &[];
pub(crate) const HUMANOID_INDICES: &[u32] = &[];
