// Generated by tools/audio_debug/export_humanoid_cc0.py.
//
// Source target:
//   Human Head 250 verts
//   Author: WeaponGuy
//   License: CC0
//   Original file: nicehumanmodel.blend (Layer 1: low-poly head with eyes, not subsurfed)
//   https://opengameart.org/content/human-head-250-verts
//
// The repository keeps an empty generated payload so normal builds do not depend on Blender or a
// network download. The 3D debug view uses its rounded low-poly head fallback until the exact CC0
// Layer-1 mesh is baked into this file; DSP ear positions never depend on this visual asset.

pub(crate) const HUMANOID_ASSET_READY: bool = false;
pub(crate) const HUMANOID_VERTICES: &[[f32; 3]] = &[];
pub(crate) const HUMANOID_INDICES: &[u32] = &[];
