[package]
name = "lucide-gpui"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[lints.rust]
unsafe_code = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"

[dependencies]
gpui = { git = "https://github.com/Chlna6666/Better-Minecraft-Bedrock-Launcher.git", rev = "6ac0201acd1b7c703a58dc4150585c42b2d28e00", default-features = false }
anyhow = "1.0.100"
