[package]
name = "lucide-gpui"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"

[lints.rust]
unsafe_code = "warn"

[lints.clippy]
all = "warn"
pedantic = "warn"

[dependencies]
gpui = { git = "https://github.com/Chlna6666/Better-Minecraft-Bedrock-Launcher.git", rev = "526fb7885286cacb5058f0ac44f1328f3392b8d5", default-features = false }
anyhow = "1.0.100"
